package com.sinosoft.ddss.dao;

import com.sinosoft.ddss.common.entity.CollectionReport;
import java.math.BigDecimal;

public interface CollectionReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_collection_report
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigDecimal dtplanId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_collection_report
     *
     * @mbg.generated
     */
    int insert(CollectionReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_collection_report
     *
     * @mbg.generated
     */
    int insertSelective(CollectionReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_collection_report
     *
     * @mbg.generated
     */
    CollectionReport selectByPrimaryKey(BigDecimal dtplanId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_collection_report
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CollectionReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_collection_report
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CollectionReport record);
}