package com.sinosoft.ddss.dao;

import com.sinosoft.ddss.common.entity.CustomReport;
import java.math.BigDecimal;

public interface CustomReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_custom_report
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigDecimal reportId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_custom_report
     *
     * @mbg.generated
     */
    int insert(CustomReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_custom_report
     *
     * @mbg.generated
     */
    int insertSelective(CustomReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_custom_report
     *
     * @mbg.generated
     */
    CustomReport selectByPrimaryKey(BigDecimal reportId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_custom_report
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CustomReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_custom_report
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CustomReport record);
}