package com.sinosoft.ddss.dao;

import com.sinosoft.ddss.common.entity.DedicatedUser;
import com.sinosoft.ddss.common.entity.OrderInfo;
import com.sinosoft.ddss.common.entity.query.DedicatedQuery;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface DedicatedUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_dedicated_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_dedicated_user
     *
     * @mbg.generated
     */
    int insert(DedicatedUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_dedicated_user
     *
     * @mbg.generated
     */
    int insertSelective(DedicatedUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_dedicated_user
     *
     * @mbg.generated
     */
    DedicatedUser selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_dedicated_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DedicatedUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_dedicated_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DedicatedUser record);

	List<DedicatedUser> selectByDedicatedId(String id);

	int deleteByDedicatedId(String id);

	int insertByList(@Param("list")List<DedicatedUser> list);

	DedicatedUser getDedicatedAuthBuId(BigDecimal userId);

}