package com.sinosoft.ddss.dao;

import com.sinosoft.ddss.common.entity.DedicatedLine;
import com.sinosoft.ddss.common.entity.DedicatedUser;
import com.sinosoft.ddss.common.entity.FtpUser;
import com.sinosoft.ddss.common.entity.OrderInfo;
import com.sinosoft.ddss.common.entity.query.DedicatedQuery;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface DedicatedLineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_dedicated_line
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_dedicated_line
     *
     * @mbg.generated
     */
    int insert(DedicatedLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_dedicated_line
     *
     * @mbg.generated
     */
    int insertSelective(DedicatedLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_dedicated_line
     *
     * @mbg.generated
     */
    DedicatedLine selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_dedicated_line
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DedicatedLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_dedicated_line
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DedicatedLine record);
    
    Integer countDedicatedLine(DedicatedQuery dedicatedQuery);

	List<DedicatedLine> listDedicatedLine(DedicatedQuery dedicatedQuery);

	DedicatedLine checkFtpName(String ftpName);
}