package com.sinosoft.ddss.dao;

import com.sinosoft.ddss.common.entity.Dictionary;
import java.math.BigDecimal;

public interface DictionaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_dictionary
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigDecimal dicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_dictionary
     *
     * @mbg.generated
     */
    int insert(Dictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_dictionary
     *
     * @mbg.generated
     */
    int insertSelective(Dictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_dictionary
     *
     * @mbg.generated
     */
    Dictionary selectByPrimaryKey(BigDecimal dicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_dictionary
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Dictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_dictionary
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Dictionary record);
}