package com.sinosoft.ddss.dao;

import com.sinosoft.ddss.common.entity.FtpDownload;
import java.math.BigDecimal;

public interface FtpDownloadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_ftp_download
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigDecimal orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_ftp_download
     *
     * @mbg.generated
     */
    int insert(FtpDownload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_ftp_download
     *
     * @mbg.generated
     */
    int insertSelective(FtpDownload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_ftp_download
     *
     * @mbg.generated
     */
    FtpDownload selectByPrimaryKey(BigDecimal orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_ftp_download
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FtpDownload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_ftp_download
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FtpDownload record);
}