package com.sinosoft.ddss.dao;

import com.sinosoft.ddss.common.entity.FtpUser;
import com.sinosoft.ddss.common.entity.query.FtpQuery;

import java.math.BigDecimal;
import java.util.List;

public interface FtpUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_ftpuser
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_ftpuser
     *
     * @mbg.generated
     */
    int insert(FtpUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_ftpuser
     *
     * @mbg.generated
     */
    int insertSelective(FtpUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_ftpuser
     *
     * @mbg.generated
     */
    FtpUser selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_ftpuser
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FtpUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_ftpuser
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FtpUser record);

	List<FtpUser> listFtpUser(FtpQuery ftpQuery);

	Integer countFtpUser(FtpQuery ftpQuery);

	FtpUser checkFtpName(String ftpName);
}