package com.sinosoft.ddss.dao;

import com.sinosoft.ddss.common.entity.QueryHistory;
import java.math.BigDecimal;

public interface QueryHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_shp_query_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_shp_query_history
     *
     * @mbg.generated
     */
    int insert(QueryHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_shp_query_history
     *
     * @mbg.generated
     */
    int insertSelective(QueryHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_shp_query_history
     *
     * @mbg.generated
     */
    QueryHistory selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_shp_query_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QueryHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_shp_query_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QueryHistory record);
}