package com.sinosoft.ddss.dao;

import com.sinosoft.ddss.common.entity.Role;
import com.sinosoft.ddss.common.entity.RoleResource;
import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface RoleResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_role_resource
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_role_resource
     *
     * @mbg.generated
     */
    int insert(RoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_role_resource
     *
     * @mbg.generated
     */
    int insertSelective(RoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_role_resource
     *
     * @mbg.generated
     */
    RoleResource selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_role_resource
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_role_resource
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RoleResource record);

	List<RoleResource> getRoleResourceInfoByRoleIdList(List<BigDecimal> roleIdList);

	int deleteByRoleId(BigDecimal roleId);
	int getCountByRoleId(BigDecimal roleId);

	Integer insertRoleResourceByList(@Param("list")List<RoleResource> list);

}