package com.sinosoft.ddss.dao;

import com.sinosoft.ddss.common.entity.SysLog;
import com.sinosoft.ddss.common.entity.query.SysLogQuery;

import java.math.BigDecimal;
import java.util.List;

public interface SysLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_log
     *
     * @mbg.generated
     */
    int insert(SysLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_log
     *
     * @mbg.generated
     */
    int insertSelective(SysLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_log
     *
     * @mbg.generated
     */
    SysLog selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysLog record);

	List<SysLog> listLog(SysLogQuery sysLogQuery);

	Integer countLog(SysLogQuery sysLogQuery);

	List<SysLog> listLogByIds(SysLog sysLog);
}