package com.sinosoft.ddss.dao;

import com.sinosoft.ddss.common.entity.SysResource;
import com.sinosoft.ddss.common.entity.query.SysResourceQuery;

import java.math.BigDecimal;
import java.util.List;

public interface SysResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_resource
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigDecimal resourceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_resource
     *
     * @mbg.generated
     */
    int insertSelective(SysResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_resource
     *
     * @mbg.generated
     */
    SysResource selectByPrimaryKey(BigDecimal resourceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_resource
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysResource record);

	List<SysResource> listSysResource(BigDecimal userId);

	List<SysResource> findAll();

	List<SysResource> listReource(SysResourceQuery sysResource);

	Integer countSource(SysResourceQuery sysResource);

	List<SysResource> getAllMenuResources();
	
	List<SysResource> selectByResourceid(String resourceid);
	
	List<SysResource> selectByPid(String pid);

	List<SysResource> listAuothMenu(String userId, String type);
}