package com.sinosoft.ddss.dao;

import com.sinosoft.ddss.common.entity.Task;
import java.math.BigDecimal;

public interface TaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_task
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigDecimal taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_task
     *
     * @mbg.generated
     */
    int insert(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_task
     *
     * @mbg.generated
     */
    int insertSelective(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_task
     *
     * @mbg.generated
     */
    Task selectByPrimaryKey(BigDecimal taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_task
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_task
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Task record);
}