package com.sinosoft.ddss.dao;

import com.sinosoft.ddss.common.entity.UserCount;
import java.math.BigDecimal;

public interface UserCountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_user_count
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_user_count
     *
     * @mbg.generated
     */
    int insert(UserCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_user_count
     *
     * @mbg.generated
     */
    int insertSelective(UserCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_user_count
     *
     * @mbg.generated
     */
    UserCount selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_user_count
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_user_count
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserCount record);
}