package com.sinosoft.ddss.dao;

import com.sinosoft.ddss.common.entity.UserRole;
import java.math.BigDecimal;
import java.util.List;

public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_user_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_user_role
     *
     * @mbg.generated
     */
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_user_role
     *
     * @mbg.generated
     */
    int insertSelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_user_role
     *
     * @mbg.generated
     */
    UserRole selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_user_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_sys_user_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserRole record);

	List<UserRole> listOfUserRoleById(BigDecimal userId);

	int deleteByUserId(BigDecimal userId);

	UserRole getRoleIdByUserId(BigDecimal userId);

	Integer getCountByRoleId(BigDecimal roleId);
}