package com.sinosoft.ddss.dao;

import java.util.List;

import com.sinosoft.ddss.common.entity.UserTask;

public interface UserTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_user_task
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_user_task
     *
     * @mbg.generated
     */
    int insertSelective(UserTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_user_task
     *
     * @mbg.generated
     */
    UserTask selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_user_task
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserTask record);

    //查询 用户任务表
	List<UserTask> listUserTask();

	//删除用户
	void deleteByIds(String ids);

}