package com.sinosoft.ddss.dataDao;

import com.sinosoft.ddss.common.entity.States;

public interface StatesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table states
     *
     * @mbg.generated
     */
    int insert(States record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table states
     *
     * @mbg.generated
     */
    int insertSelective(States record);
}