package com.sinosoft.ddss.dataDao;

import com.sinosoft.ddss.common.entity.World;

public interface WorldMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table world
     *
     * @mbg.generated
     */
    int insert(World record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table world
     *
     * @mbg.generated
     */
    int insertSelective(World record);
}