eureka:
  client:
    serviceUrl:
#         defaultZone: http://127.0.0.1:8761/eureka/
#        defaultZone: http://172.16.25.105:8761/eureka/
          defaultZone: http://172.16.25.27:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    # 每间隔1s，向服务端发送一次心跳，证明自己依然”存活“
    lease-renewal-interval-in-seconds: 10
    # 告诉服务端，如果我2s之内没有给你发心跳，就代表我“死”了，将我踢出掉。
    lease-expiration-duration-in-seconds: 20
 #服务端口号
server:
  port: 8178
spring:
  application:
  #服务名称
    name: feign-user
   #配置中心配置 
  #cloud:
  #  config:
  #    label: master
  #    profile: dev
  #    discovery:
  #      enabled: true
  #      serviceId: config-server  
  rabbitmq:
    host: 172.16.25.104
    port: 5672
    username: hyj
    password: hyj
    publisher-confirms: true
    virtual-host: /  
    
#####################################################################################################
# pgsql 属性配置
  datasource:
    greplum:  
      driver-class-name: org.postgresql.Driver
      #url: jdbc:postgresql://192.168.6.77:5432/hyjdb?useUnicode=true&characterEncoding=utf8
      #username: hyj
      #password: hyj
      url: jdbc:postgresql://172.16.17.133:5432/gpdb?useUnicode=true&characterEncoding=utf8
      username: gpuser
      password: gpuser123456
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800 
    postgre:
      driver-class-name: org.postgresql.Driver
      #url: jdbc:postgresql://192.168.6.77:5432/hyjdb?useUnicode=true&characterEncoding=utf8
      #username: hyj
      #password: hyj
      url: jdbc:postgresql://172.16.17.137:5432/postgres?useUnicode=true&characterEncoding=utf8
      username: postgres
      password: postgres
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
  #jpa:
 #   database-platform: org.hibernate.dialect.MySQL5Dialect 
#    hibernate:
      #ddl-auto: create #ddl-auto:设为create表示每次都重新建表
 #     ddl-auto: update #ddl-auto:设为update表示每次都不会重新建表
 #   show-sql: true
#####################################################################################################

#####################################################################################################
# mybatis mapper xml 配置
mybatis:
  # mybatis.type-aliases-package：指定domain类的基包，即指定其在*Mapper.xml文件中可以使用简名来代替全类名（看后边的CityMapper.xml介绍）
  typeAliasesPackage: com.sinosoft.ddss.common.entity
  mapperLocations: classpath:mapper/*.xml,dataMapper/*.xml
#####################################################################################################
#rabbitmq: 
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#    publisher-confirms: true
#    virtual-host: /
#####################################################################################################
# 打印日志
logging:
  level:
    root: INFO
    org.spring: DEBUG
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.springms: DEBUG
    com.sinosoft.ddss.dao: TRACE
    path: /log
#####################################################################################################